#!/bin/bash
if [ -z $1 ] 
then
  DOCKERCONTAINER=opencoral
else
  DOCKERCONTAINER=$1
fi
dockerssh() {
  ssh -Y -i chef/base/secret/id_rsa -p $(docker port $1 22 | cut -d: -f2)  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no coral@localhost
}
dockerssh $DOCKERCONTAINER
