#!/bin/bash
EXAMPLEDATABAG=$(cat <<EOF
{
  "id": "general",
  "postgres": "postgres",
  "coraldba": "coraldba",
  "root": "rootpass-1234",
  "coral_storepass": "storepass-1234",
  "coral_keypass": "keypass-1234"
}
EOF
)

#first check if secrets file exists
if [ ! -f /chef/data_bags/passwords/opencoral.json ]
then 
	echo "***************************************************************************"; 
	echo
	echo "No passwords file found. Please create one."; 
	echo "quickstart: cp chef/base/data_bags/passwords/opencoral.json.template chef/base/data_bags/passwords/opencoral.json"
	echo 
	echo "***************************************************************************"; 
	exit 1
fi


